### ISSUE TITLE
Add registry keys to ensure XHR tests can find Perl

### ISSUE THREAD

**Issue by rkirsling** [WebKitForWindows/docker-webkit-dev#7]
(From https://bugs.webkit.org/show_bug.cgi?id=188039.)

90 tests under `http/tests/xmlhttprequest` fail if Perl can't be located.

Solution:
```
reg add HKEY_CLASSES_ROOT\.pl\Shell\ExecCGI\Command /ve /d "C:\tools\perl\perl\bin\perl.exe -T"
reg add HKEY_CLASSES_ROOT\.cgi\Shell\ExecCGI\Command /ve /d "C:\tools\perl\perl\bin\perl.exe -T"
```

**Comment by donny-dont** [comment]
Believe this is fixed now in 743a9a20d0d2533768ec26cfe6b4746b70f83bc6

**Comment by fujii** [comment]
Reopen this issue. It is not fixed yet. You set values to wrong registry paths. Use ｀(Default)｀ http://powershelleverydayfaq.blogspot.com/2012/08/how-to-work-with-registry-default-values.html

**Comment by donny-dont** [comment]
This is fixed in https://github.com/WebKitForWindows/powershell-webkit-dev/commit/7911b33efa1b0da41c014cff35d0422a4478b4a0 based on above comment.
